myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static

def redirect_to_home(request):
    return redirect('home')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),  # 유저 관련 URL들
    path('', redirect_to_home),  # 기본 페이지 접근 시 home으로 이동
    path('home/', include('user.urls')),
    path('post/', include('post.urls')),
    path('profile/', include('user_profile.urls')),
    path('accounts/',include('allauth.urls')),
]

# 미디어 파일 개발 환경에서 보이게 하기
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('create/', views.post_create, name='post_create'),
    path('<int:pk>/', views.post_detail, name='post_detail'),
    path('<int:pk>/comment/', views.add_comment, name='add_comment'),
    path('<int:pk>/like/', views.toggle_post_like, name='toggle_post_like'),
    path('comment/<int:pk>/like/', views.toggle_comment_like, name='toggle_comment_like'),
    path('edit/<int:id>/', views.post_edit, name='post_edit'),
    path('delete/<int:id>/', views.post_delete, name='post_delete'),
]

post/models.py
from django.db import models
from django.conf import settings

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = models.ImageField(upload_to='post_images/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    view_count = models.PositiveIntegerField(default=0) 
    
    TECH_STACK_CHOICES = [
        ('python', 'Python'),
        ('django', 'Django'),
        ('react', 'React'),
        ('kotlin', 'Kotlin'),
        ('flutter', 'Flutter'),
    ]
    tech_stack = models.CharField(max_length=100, choices=TECH_STACK_CHOICES, blank=True)
    github_link = models.URLField(blank=True, null=True)

    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='liked_posts', blank=True)

    def __str__(self):
        return self.title
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='liked_comments', blank=True)

    def __str__(self):
        return f"{self.user.username} - {self.content[:20]}"

post/forms.py
# post/forms.py

from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'image', 'tech_stack', 'github_link']  # 필요한 필드만 지정

post/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from .models import Post, Comment
from django.db.models import Q 
from django.db.models import Count
from django.contrib import messages
from .models import Post
from .forms import PostForm


def post_create(request):
    if request.method == 'POST':
        title = request.POST['title']
        content = request.POST['content']
        image = request.FILES.get('image')  
        tech_stack = request.POST.get('tech_stack')
        github_link = request.POST.get('github_link')

        Post.objects.create(
            author=request.user,
            title=title,
            content=content,
            image=image,
            tech_stack=tech_stack,
            github_link=github_link
        )
        return redirect('post_list')
    
    return render(request, 'post/post_create.html')


def post_list(request):
    sort = request.GET.get('sort', '')
    q = request.GET.get('q', '')

    if q == "None":
        q = ""

    posts = Post.objects.all()

    # 검색어가 있으면 제목 기준 필터링
    if q:
        posts = posts.filter(title__icontains=q)

    # 정렬 처리
    if sort == 'popular':
        posts = posts.annotate(likes_count=Count('likes')).order_by('-likes_count', '-created_at')
    else:
        posts = posts.order_by('-created_at')

    return render(request, 'post/post_list.html', {'posts': posts, 'sort': sort, 'q': q})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)

    session_key = f'viewed_post_{pk}'
    if not request.session.get(session_key, False):
        post.view_count += 1
        post.save()
        request.session[session_key] = True

    comments = post.comments.filter(parent=None)
    return render(request, 'post/post_detail.html', {
        'post': post,
        'comments': comments
    })


def add_comment(request, pk):
    if request.method == "POST":
        post = get_object_or_404(Post, pk=pk)
        content = request.POST['content']
        parent_id = request.POST.get('parent_id')
        parent_comment = Comment.objects.get(pk=parent_id) if parent_id else None
        Comment.objects.create(post=post, user=request.user, content=content, parent=parent_comment)
        return redirect('post_detail', pk=pk)


@login_required
def toggle_post_like(request, pk):
    post = Post.objects.get(pk=pk)
    if request.user in post.likes.all():
        post.likes.remove(request.user)
        liked = False
    else:
        post.likes.add(request.user)
        liked = True
    return JsonResponse({'liked': liked, 'likes_count': post.likes.count()})


@login_required
def toggle_comment_like(request, pk):
    comment = Comment.objects.get(pk=pk)
    if request.user in comment.likes.all():
        comment.likes.remove(request.user)
        liked = False
    else:
        comment.likes.add(request.user)
        liked = True
    return JsonResponse({'liked': liked, 'likes_count': comment.likes.count()})


@login_required
def post_edit(request, id):
    post = get_object_or_404(Post, id=id)

    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            messages.success(request, '게시물이 수정되었습니다.')
            return redirect('post_list')  # 수정 후 게시물 목록으로 리디렉션
    else:
        form = PostForm(instance=post)

    return render(request, 'post/post_edit.html', {'form': form, 'post': post})

# 게시물 삭제
@login_required
def post_delete(request, id):
    post = get_object_or_404(Post, id=id)

    if request.method == 'POST':
        post.delete()
        messages.success(request, '게시물이 삭제되었습니다.')
        return redirect('post_list')  # 삭제 후 게시물 목록으로 리디렉션

    return render(request, 'post/post_confirm_delete.html', {'post': post})

post/templates/post/post_confirm_delete.html
<!-- post/post_confirm_delete.html -->

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>게시물 삭제</title>
</head>
<body>
    <h1>{{ post.title }} 게시물을 삭제하시겠습니까?</h1>

    <form method="POST">
        {% csrf_token %}
        <button type="submit">삭제</button>
    </form>

    <a href="{% url 'post_list' %}">취소</a>
</body>
</html>

post/templates/post/post_create.html
<h2>게시글 작성</h2>
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <label>제목:</label><br>
  <input type="text" name="title"><br><br>

  <label>내용:</label><br>
  <textarea name="content" rows="5" cols="40"></textarea><br><br>

  <label>이미지:</label><br>
  <input type="file" name="image"><br><br>

  <label>기술 스택:</label><br>
  <select name="tech_stack">
    <option value="">--선택--</option>
    <option value="python">Python</option>
    <option value="django">Django</option>
    <option value="react">React</option>
    <option value="kotlin">Kotlin</option>
    <option value="flutter">Flutter</option>
  </select><br><br>

  <label>깃허브 링크:</label><br>
  <input type="url" name="github_link"><br><br>

  <button type="submit">작성</button>
</form>

post/templates/post/post_detail.html
{% load static %}

{% block content %}
<h2>{{ post.title }}</h2>
<p>
  <a href="{% url 'profile_view' post.author.username %}">
    {{ post.author.username }}
  </a> | {{ post.created_at }}
</p>
<p>{{ post.content|linebreaks }}</p>


<p>{{ post.content|linebreaks }}</p>

{% if post.image %}
  <div>
    <img src="{{ post.image.url }}" alt="Post Image" style="max-width: 100%; height: auto; margin-top: 10px;">
  </div>
{% endif %}

{% if post.tech_stack %}
  <p><strong>기술 스택:</strong> {{ post.get_tech_stack_display }}</p>
{% endif %}

{% if post.github_link %}
  <p><strong>GitHub 링크:</strong> 
    <a href="{{ post.github_link }}" target="_blank">{{ post.github_link }}</a>
  </p>
{% endif %}


<!-- 게시글 좋아요 버튼 -->
<button class="like-post-btn" data-post-id="{{ post.pk }}">
  <span class="like-text">
    {% if user in post.likes.all %}
      💖 좋아요
    {% else %}
      🤍 좋아요
    {% endif %}
  </span>
  (<span class="like-count">{{ post.likes.count }}</span>)
</button>

<hr>

<h3>댓글</h3>
{% for comment in comments %}
  <div style="margin-left: 0;">
    <strong>{{ comment.user.username }}</strong>: {{ comment.content }} ({{ comment.created_at }})

    <!-- 댓글 좋아요 버튼 -->
    <button class="like-comment-btn" data-comment-id="{{ comment.pk }}">
      <span class="like-text">
        {% if user in comment.likes.all %}
          💖 좋아요
        {% else %}
          🤍 좋아요
        {% endif %}
      </span>
      (<span class="like-count">{{ comment.likes.count }}</span>)
    </button>

    <form method="post" action="{% url 'add_comment' post.pk %}">
      {% csrf_token %}
      <input type="hidden" name="parent_id" value="{{ comment.id }}">
      <input type="text" name="content" placeholder="답글 달기">
      <button type="submit">작성</button>
    </form>

    {% for reply in comment.replies.all %}
      <div style="margin-left: 20px;">
        <strong>{{ reply.user.username }}</strong>: {{ reply.content }} ({{ reply.created_at }})

        <!-- 대댓글 좋아요 버튼 -->
        <button class="like-comment-btn" data-comment-id="{{ reply.pk }}">
          <span class="like-text">
            {% if user in reply.likes.all %}
              💖 좋아요
            {% else %}
              🤍 좋아요
            {% endif %}
          </span>
          (<span class="like-count">{{ reply.likes.count }}</span>)
        </button>
      </div>
    {% endfor %}
  </div>
  {% endfor %}



<form method="post" action="{% url 'add_comment' post.pk %}">
  {% csrf_token %}
  <textarea name="content" placeholder="댓글 작성"></textarea>
  <button type="submit">작성</button>
</form>


<!-- 좋아요 비동기 처리 JS -->
<script>
  document.addEventListener('DOMContentLoaded', function () {
    // 게시글 좋아요
    document.querySelectorAll('.like-post-btn').forEach(button => {
      button.addEventListener('click', function (e) {
        e.preventDefault();
        const postId = this.dataset.postId;
        fetch(`/post/${postId}/like/`, {
          method: 'POST',
          headers: {
            'X-CSRFToken': getCookie('csrftoken'),
            'X-Requested-With': 'XMLHttpRequest',
          },
        })
        .then(response => response.json())
        .then(data => {
          this.querySelector('.like-count').textContent = data.likes_count;
          this.querySelector('.like-text').textContent = data.liked ? '💖 좋아요' : '🤍 좋아요';
        });
      });
    });

    // 댓글 & 대댓글 좋아요
    document.querySelectorAll('.like-comment-btn').forEach(button => {
      button.addEventListener('click', function (e) {
        e.preventDefault();
        const commentId = this.dataset.commentId;
        fetch(`/post/comment/${commentId}/like/`, {
          method: 'POST',
          headers: {
            'X-CSRFToken': getCookie('csrftoken'),
            'X-Requested-With': 'XMLHttpRequest',
          },
        })
        .then(response => response.json())
        .then(data => {
          this.querySelector('.like-count').textContent = data.likes_count;
          this.querySelector('.like-text').textContent = data.liked ? '💖 좋아요' : '🤍 좋아요';
        });
      });
    });

    // CSRF 토큰 가져오기
    function getCookie(name) {
      let cookieValue = null;
      if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let cookie of cookies) {
          cookie = cookie.trim();
          if (cookie.substring(0, name.length + 1) === (name + '=')) {
            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
            break;
          }
        }
      }
      return cookieValue;
    }
  });
</script>

{% endblock %}

post/templates/post/post_edit.html
<!-- post/post_edit.html -->

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>게시물 수정</title>
</head>
<body>
    <h1>{{ post.title }} 게시물 수정</h1>
    
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">수정</button>
    </form>
    <a href="{% url 'post_list' %}">게시물 목록으로 돌아가기</a>
</body>
</html>

post/templates/post/post_list.html
<h1>📚 게시글 목록</h1>

<form method="get" action="{% url 'post_list' %}">
    <input type="text" name="q" value="{{ q }}" placeholder="검색어를 입력하세요">
    <input type="submit" value="검색">
    {% if sort %}
        <input type="hidden" name="sort" value="{{ sort }}">
    {% endif %}
</form>

<div>
    <strong>정렬:</strong>
    <a href="?sort=&q={{ query|urlencode }}" {% if sort == "" or not sort %}style="font-weight:bold"{% endif %}>최신순</a> |
    <a href="?sort=popular&q={{ query|urlencode }}" {% if sort == "popular" %}style="font-weight:bold"{% endif %}>인기순</a>
</div>

<a href="{% url 'post_create' %}">
    <button>✍️ 게시글 작성하러 가기</button>
</a>

<hr>

{% if posts %}
    {% for post in posts %}
        <h2><a href="{% url 'post_detail' post.pk %}">{{ post.title }}</a></h2>
        <p>작성자: {{ post.author.username }} | 작성일: {{ post.created_at }}</p>
        <p>조회수: {{ post.view_count }}</p>
    {% endfor %}
{% else %}
    <p>게시글이 없습니다.</p>
{% endif %}